# -*- coding: utf-8 -*-
"""hana-cara.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Amkkp0PILvf547PS8bgrbVhXgHhKgWBu
"""

from google.colab import drive
drive.mount('/content/drive')

print("hellow word")