name: chatgpt

on:
  push:
    branches:
      - main  # Change this to your branch name if different
  workflow_dispatch:

jobs:
  run_notebook:
    runs-on: self-hosted  # This ensures it uses a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements file
          # Install any other dependencies if needed

      - name: Run Jupyter Notebook
        run: jupyter nbconvert --to notebook --execute hana_cara.ipynb --output executed_notebook.ipynb
